<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>NABAMS Election Results</title>
        <style>
            * {
                box-sizing: border-box;
            }

            body {
                color: #2E2E2E;
                font-family: DejaVu Sans, sans-serif;
                font-size: 11px;
                line-height: 1.45;
                margin: 0;
            }

            .header {
                background: #0A2A6B;
                color: #FFFFFF;
                padding: 22px;
            }

            .header h1 {
                font-size: 24px;
                margin: 4px 0 0;
            }

            .header p {
                margin: 4px 0 0;
            }

            .meta {
                background: #F2F2F2;
                border-bottom: 1px solid #D8DDE8;
                padding: 12px 22px;
            }

            .content {
                padding: 18px 22px;
            }

            h2 {
                color: #0A2A6B;
                font-size: 16px;
                margin: 18px 0 8px;
            }

            h3 {
                color: #0A2A6B;
                font-size: 13px;
                margin: 14px 0 6px;
            }

            table {
                border-collapse: collapse;
                margin-bottom: 14px;
                width: 100%;
            }

            th {
                background: #0A2A6B;
                color: #FFFFFF;
                font-size: 10px;
                padding: 7px;
                text-align: left;
            }

            td {
                border: 1px solid #D8DDE8;
                padding: 7px;
                vertical-align: top;
            }

            .summary td {
                font-weight: bold;
            }

            .gold {
                color: #F5B400;
                font-weight: bold;
            }

            .green {
                color: #1FA774;
                font-weight: bold;
            }

            .muted {
                color: #666666;
            }

            .page-break {
                page-break-before: always;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="gold">NABAMS ELECTION REPORT</div>
            <h1>Election Results</h1>
            <p>{{ $selectedSession?->name ?? 'No session selected' }}</p>
        </div>

        <div class="meta">
            <strong>Generated by:</strong> {{ $generatedBy->name ?: $generatedBy->email }}
            &nbsp; | &nbsp;
            <strong>Generated at:</strong> {{ $generatedAt->format('M d, Y h:i A') }}
            &nbsp; | &nbsp;
            <strong>Report type:</strong>Vote Summary 
        </div>

        <div class="content">
            <h2>Official Results Summary</h2>

            @forelse ($positions as $position)
                @php
                    $positionAdjustmentTotal = (int) ($positionAdjustmentTotals[$position->id]->adjustment_total ?? 0);
                    $positionOfficialTotal = max(0, $position->votes_count + $positionAdjustmentTotal);
                @endphp

                <h3>{{ $position->name }}</h3>
                {{-- <table class="summary">
                    <tr>
                        <td>Official Total: {{ $positionOfficialTotal }}</td>
                        <td>Member Votes: {{ $position->votes_count }}</td>
                        <td>Adjustments: {{ $positionAdjustmentTotal >= 0 ? '+' : '' }}{{ $positionAdjustmentTotal }}</td>
                    </tr>
                </table> --}}

                <table>
                    <thead>
                        <tr>
                            <th>Aspirant</th>
                            {{-- <th>Member Votes</th>
                            <th>Adjustments</th> --}}
                            <th>Official Total</th>
                            <th>Percent</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($position->aspirants->sortByDesc(function ($aspirant) use ($position, $voteTotals, $adjustmentTotals) {
                            $key = $position->id.':'.$aspirant->id;

                            return (int) ($voteTotals[$key]->vote_total ?? 0) + (int) ($adjustmentTotals[$key]->adjustment_total ?? 0);
                        }) as $aspirant)
                            @php
                                $key = $position->id.':'.$aspirant->id;
                                $memberVotes = (int) ($voteTotals[$key]->vote_total ?? 0);
                                $adjustments = (int) ($adjustmentTotals[$key]->adjustment_total ?? 0);
                                $officialTotal = max(0, $memberVotes + $adjustments);
                                $percentage = $positionOfficialTotal > 0 ? round(($officialTotal / $positionOfficialTotal) * 100, 2) : 0;
                            @endphp
                            <tr>
                                <td>{{ $aspirant->name }}</td>
                                {{-- <td>{{ $memberVotes }}</td>
                                <td>{{ $adjustments >= 0 ? '+' : '' }}{{ $adjustments }}</td> --}}
                                <td class="green">{{ $officialTotal }}</td>
                                <td>{{ $percentage }}%</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="muted">No aspirants assigned to this position.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            @empty
                <p class="muted">No election position for this session.</p>
            @endforelse

            <div class="page-break"></div>

            <h2>Vote Adjustment Audit Log</h2>
            <p class="muted">Adjustments are recorded separately from member ballot records.</p>

            <table>
                <thead>
                    <tr>
                        <th>Time</th>
                        <th>Admin</th>
                        <th>Position</th>
                        <th>Aspirant</th>
                        <th>Change</th>
                        <th>Before</th>
                        <th>After</th>
                        <th>Reason</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($allAdjustments as $adjustment)
                        <tr>
                            <td>{{ $adjustment->created_at?->format('M d, Y h:i A') }}</td>
                            <td>{{ $adjustment->admin?->name ?? 'Deleted admin' }}</td>
                            <td>{{ $adjustment->position?->name }}</td>
                            <td>{{ $adjustment->aspirant?->name }}</td>
                            <td>{{ $adjustment->adjustment >= 0 ? '+' : '' }}{{ $adjustment->adjustment }}</td>
                            <td>{{ $adjustment->before_total }}</td>
                            <td>{{ $adjustment->after_total }}</td>
                            <td>{{ $adjustment->reason }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="8" class="muted">No vote adjustments recorded for this session.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </body>
</html>
